module.exports.userService = require('./user.service')
module.exports.roleService = require('./role.service')
module.exports.permissionService = require('./permission.service')
module.exports.rolePermissionService = require('./rolePermission.service')
module.exports.authService = require('./auth.service')